# config.yml

backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: "assets/images"
collections:
  - name: "Sections"
    label: "Sections"
    files:
      - label: "About film"
        name: "About"
        file: "_includes/about-film.html"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Content, name: content, widget: markdown }
